# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10

  - name: Experience
    weight: 20
    identifier: 'experience'
  - name: Work and research
    url: '#experience_work_research'
    weight: 21
    parent: 'experience'
  - name: Teaching
    url: '#experience_teaching'
    weight: 22
    parent: 'experience'

  - name: Achievements
    url: '#achievements'
    weight: 27

  - name: Projects
    url: '#projects'
    weight: 30

  - name: Publications
    url: '#publications'
    weight: 40

  - name: Contact
    url: '#contact'
    weight: 45

  - name: CV
    url: https://drive.google.com/file/d/1_cLCcJ0gy_y6V9iPC8RACf5IYLDISoVj/view?usp=sharing
    weight: 50

  # Siapa tau nanti kepake
  # - name: Posts
  #   url: '#posts'
  #   weight: 20
  # - name: Talks
  #   url: '#talks'
  #   weight: 40